# ~/.config/starship.toml



# [î‚¶](fg:#98E024)\
# [ ï…º ](bg:#98E024 fg:#0C0C0C)\
# [î‚°](fg:#98E024)\

# [î‚¶](#9A348E)\
# [ï…º](bg:#9A348E)\
# [î‚°](bg:#DA627D fg:#9A348E)\
# $directory\
# [î‚°](fg:#DA627D bg:#FCA17D)\
# $git_branch\
# $git_status\
# [î‚°](fg:#FCA17D bg:#86BBD8 fg:#0C0C0C)\
# $c\
# $elixir\
# $elm\
# $golang\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# [î‚°](fg:#86BBD8 bg:#06969A)\
# $docker_context\
# [î‚°](fg:#06969A bg:#33658A)\
# $time\
# [î‚° ](fg:#33658A)\


format = """
$status
[î‚¶](fg:#F4005F)\
[ ï¡± ](bg:#F4005F fg:#0C0C0C)\
[î‚°](bg:#98E024 fg:#F4005F)\
$directory\
[î‚°](bg:#FD971F fg:#98E024)\
$git_branch\
$git_status\
[î‚°](fg:#FD971F bg:#58D1EB)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$python\
[î‚°](fg:#58D1EB bg:#06969A)\
$docker_context\
[î‚°](fg:#06969A bg:#33658A)\
$time\
[î‚° ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'


[directory]
style = "bg:#98E024 fg:#0C0C0C"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜ "
style = "bg:#86BBD8 fg:#0C0C0C"
format = '[[ $symbol ($version) ](bg:#86BBD8 fg:#0C0C0C)]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#86BBD8 fg:#0C0C0C"
format = '[[ $symbol ($version) ](bg:#86BBD8 fg:#0C0C0C)]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#86BBD8 fg:#0C0C0C"
format = '[[ $symbol ($version) ](bg:#86BBD8 fg:#0C0C0C)]($style)'

[git_branch]
symbol = "îœ‚"
style = "bg:#FD971F fg:#0C0C0C"
format = '[[ $symbol $branch ](bold bg:#FD971F fg:#0C0C0C)]($style)'

[git_status]
style = "bg:#FD971F fg:#0C0C0C"
format = '[[($all_status$ahead_behind )](bg:#FD971F fg:#0C0C0C)]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#86BBD8 fg:#0C0C0C"
format = '[[ $symbol ($version) ](bg:#86BBD8 fg:#0C0C0C)]($style)'

[haskell]
symbol = "î· "
style = "bg:#86BBD8 fg:#0C0C0C"
format = '[[ $symbol ($version) ](bg:#86BBD8 fg:#0C0C0C)]($style)'

[java]
symbol = "î‰– "
style = "bg:#86BBD8 fg:#0C0C0C"
format = '[[ $symbol ($version) ](bg:#86BBD8 fg:#0C0C0C)]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#86BBD8 fg:#0C0C0C"
format = '[[ $symbol ($version) ](bg:#86BBD8 fg:#0C0C0C)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#86BBD8 fg:#0C0C0C"
format = '[[ $symbol ($version) ](bg:#86BBD8 fg:#0C0C0C)]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#86BBD8 fg:#0C0C0C"
format = '[[ $symbol ($version) ](bg:#86BBD8 fg:#0C0C0C)]($style)'

[rust]
symbol = "î¨"
style = "bg:#86BBD8 fg:#0C0C0C"
format = '[[ $symbol ($version) ](bg:#86BBD8 fg:#0C0C0C)]($style)'

# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#33658A"
# format = '[[ â™¥ $time ](bg:#33658A)]($style)'

[python]
symbol = "îˆµ"
style = "bg:#86BBD8 fg:#0C0C0C"
# format = '[[ $symbol ($version)  $pyenv_prefix](bg:#86BBD8 fg:#0C0C0C)]($style)'
format = '[${symbol} ${pyenv_prefix} ${version} ${virtualenv} ]($style)'


# Clear visibility for exit codes
[status]
#style = "bg:#625E4C"
symbol = "ğŸ‘ğŸ‘ğŸ‘"
success_symbol = "ğŸ‘ğŸ‘ğŸ‘"
format = '[î‚¶[ $symbol ](bg:#263238)î‚´](fg:#263238) '
disabled = false